[package]
name = "dev_neural"
version = "0.1.0"
edition = "2024"

[dependencies]
neural = { path = "../../neural" }
burn = { version = "0.20.0-pre.5", features = ["train", "ndarray", "vision", "wgpu"] }
