[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
nn = { path = "../nn" }
chrono = "0.4.39"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
log = "0.4.24"
itertools = "0.14.0"
nalgebra = { version = "0.33.2", features = ["serde-serialize", "rand"] }